project:
  output-dir: ../docs/en
  type: website    
  resources: 
    - "/figs/*"

website:
  title: "SCO-SOC Virtual Meeting 2026"
  repo-url: https://github.com/sco-soc/Virtual2026
  repo-subdir: en
  navbar:
    left:
      - text: Welcome
        href: index.qmd
      - text: Participate
        href: participate.qmd
      - text: Program
        href: program.qmd
      - text: Sponsors
        href: sponsors.qmd
      - text: Resources
        href: resources.qmd
    right:
      - text: Code of Conduct
        href: code-of-conduct.qmd        
      - text: EN
        menu:
        - text: FR
          href: "../fr/{{< meta filename >}}.html"
  page-footer: 
    left: 
      - text: "Society of Canadian Ornithologists"
        href: https://www.sco-soc.ca
    center: 
      - text: "Code of Conduct"
        href: code-of-conduct.qmd
    right: 
      - text: "Suggest an edit to this page"
        href: https://github.com/SCO-SOC/Virtual2026/issues/new?template=edit-a-page.md
  site-url: https://sco-soc.github.io/Virtual2026/en/

  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "Details to come"
  #   type: primary
  #   position: below-navbar

format:
  html:
    respect-user-color-scheme: true
    theme:
      - flatly
      - ../res/styles.scss



