project:
  output-dir: ../docs/fr
  type: website    

website:
  title: "SCO-SOC Réunion Virtuel 2026"
  navbar:
    left:
      - text: Bienvenue
        href: index.qmd
      - text: Participer
        href: participate.qmd
      - text: Programme
        href: program.qmd
      - text: Commanditaires
        href: sponsors.qmd
      - text: Ressources
        href: resources.qmd
    right:
      - text: Code de conduite
        href: code-of-conduct.qmd
      - text: FR
        menu:
        - text: EN
          href: "../en/{{< meta filename >}}.html"
  page-footer: 
    left: 
      - text: "Société des ornithologistes du Canada"
        href: https://www.sco-soc.ca/fr
    center: 
      - text: "Code de conduite"
        href: code-of-conduct.qmd
    right: 
      - text: "Proposer une correction pour cette page"
        href: https://github.com/SCO-SOC/Virtual2026/issues/new?template=edit-a-page.md
  site-url: https://sco-soc.github.io/Virtual2026/fr
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "Détails"
  #   type: primary
  #   position: below-navbar

format:
  html:
    respect-user-color-scheme: true
    theme:
      - flatly
      - ../res/styles.scss



